### ISSUE TITLE
[fix] HTML5 validator error

### ISSUE THREAD

**Issue by ghost** [minddust/bootstrap-progressbar#27]
When you validate site when is use bootstrap-progressbar plugin get a validation errors from aria-... atributes.
To fix this problem add "data-" before aria-.. atributes, for example:

Change aria-valuetransitiongoal to data-aria-valuetransitiongoal

These changes should be made in the html file and in the file plugin.

```
40.        var aria_valuetransitiongoal = $this.attr('data-aria-valuetransitiongoal');
41.        var aria_valuemin = $this.attr('data-aria-valuemin') || 0;
42.        var aria_valuemax = $this.attr('data-aria-valuemax') || 100;
.
.
.
127.       $this.attr('data-aria-valuenow', current_value);
```

**Comment by jocar6562** [comment]
Hi
Thank you for this info passes Val no errours johnc
