### ISSUE TITLE
How to dynamically update the value of the progress bar

### ISSUE THREAD

**Issue by codecowboy** [minddust/bootstrap-progressbar#31]
is the 'update' callback suitable for making an ajax request to update the percent value or is that only for reacting to a value change? I need to update a progress bar dynamically based on the result of an ajax call.

Is there an example of this somewhere?

**Comment by suresharaka** [comment]
how to update the progress bar sliders and to show and update that progress bar slider with that percentage value in another profile
![image](https://user-images.githubusercontent.com/32697428/31425328-8479ebac-ae7c-11e7-93ee-51cae29ace4b.png)
