### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by mohsen1565** [minddust/bootstrap-progressbar#44]
Hi.
I tried to run the demo code that you provided here (vertical progressbar bottom) but I get 2 errors when I open the console and nothing shows at all. The Errors are as follows:
1- Uncaught TypeError: Cannot read property 'noop' of undefined 
2- Uncaught TypeError: undefined is not a function  (meaning the function "progressbar").
Is it possible for you to send me the whole source code for that demo, so I can run it on my computer and see where my mistake is...?
Best Regards.

**Comment by minddust** [comment]
hey @mohsen1565 

1. appears when jquery isn't loaded
2. appears when progressbar.js isn't loaded

the source of the demo is available through my github page:

https://github.com/minddust/minddust.github.io

but is in an abstract jekyll templating form. 
to run every sample on your own - a source snippet is provided under each visual demo:

http://www.minddust.com/project/bootstrap-progressbar/demo/

if I have to guess: you missed to include jquery.

good luck :)

**Comment by mohsen1565** [comment]
Dear Stefan.
I decided to send you the source code as it is not too lengthy and very
easy to read to make sure it's in line with the source code for the demo...
I have followed all instructions and made sure that the link between the
html page and js files is well established.
I would be very thankful if you can have a look at the source code.
Regards.

**Comment by minddust** [comment]
please don't send me code via mail. (btw didn't received any)

i've just set up a working jsfiddle for you:

http://jsfiddle.net/abwkorq7/

pretty straight forward. just follow the instructions and you should be good

**Comment by minddust** [comment]
if it's still not working - just make / modify that jsfiddle and i will take a look if i find some time

**Comment by mohsen1565** [comment]
Thank you very much Stefan, it's running fine now....
Regards.
