### ISSUE TITLE
progress bar bootstrap 3 not working properly in Chrome/Opera

### ISSUE THREAD

**Issue by omatic-hacker** [minddust/bootstrap-progressbar#45]
Strange bug, progress bar is not changing dynamicly in Chrome 40 , Opera.

Code from demo:
```javascript
<div class="progress">
    <div class="progress-bar" role="progressbar"></div>
</div>
<button type="button" id="trigger-0">0</button>
<button type="button" id="trigger-50">50</button>
<button type="button" id="trigger-100">100</button>

$(document).ready(function() {
    var $pb = $('.progress .progress-bar');
    $('#m-multi-trigger-0').click(function() {
        $pb.attr('data-transitiongoal', 0).progressbar({display_text: 'center'});
    });
    $('#m-multi-trigger-50').click(function() {
        $pb.attr('data-transitiongoal', 50).progressbar({display_text: 'center'});
    });
    $('#m-multi-trigger-100').click(function() {
        $pb.attr('data-transitiongoal', 100).progressbar({display_text: 'center'});
    });
});
```

When I am clicking button, progres bar % is not changing (ui also). But when i am clicking few more times at a row, some progress is strangely changing... 

Can anyone help to solve, and answer the question what is wrong ? o_O
Thanks!

P.S.Firefox/IE - all ok.

**Comment by omatic-hacker** [comment]
Also in my code, i dynamically changing %, and progress bar is not even working...

but when i duplicate code with timeouts, Chrome starts to show progress bar normally, for example:

```javascript
progressMain.attr('data-transitiongoal', progress.percentage).progressbar({display_text: 'fill'});
setTimeout(function(){progressMain.attr('data-transitiongoal', progress.percentage).progressbar({display_text: 'fill'});},300);
setTimeout(function(){progressMain.attr('data-transitiongoal', progress.percentage).progressbar({display_text: 'fill'});},100);
```

**Comment by minddust** [comment]
hi @omatic-hacker 

did you noticed the same behavior on the demo page or just in your example?

**Comment by omatic-hacker** [comment]
Hello ;)

Yes, in demo too. I tested on last example v.3.3.0 multi trigger 0 50 100 

For the first time everything is ok, but try to click buttons 0 50 100 very quickly few times one after another, then Chrome is getting crazy and "lag". After that, even if you click button slowly, progress bar is strangely showing percentage.

**Comment by omatic-hacker** [comment]
P.P.S. lately i was investigating it on chromium builds, and on build 42.0.2293.0 everything works fine and "lags" don't appear,

**Comment by minddust** [comment]
just tested the demo with chrome 40.0.2214.94 on mac. looks fine to me. 

maybe this was a local problem? mix of empty ram --> laggy browser?

you're welcome :)
