### ISSUE TITLE
Callback function "done" fires immediately

### ISSUE THREAD

**Issue by talena6** [minddust/bootstrap-progressbar#47]
Hi, I'm not good with js/jquery, can you please let me know why this isn't working? It removes/replaces the class before the progress bar loads.

I have this at the bottom of my html file, before the closing body tag, after bootstrap-progressbar.js:

    <script>
        $(document).ready(function() {
            $('.progress .progress-bar').progressbar({
              done: $('.loading').removeClass('loading').addClass('loaded')
            });
        });
    </script>

**Comment by ptihiy** [comment]
That's simple: you should pass closure.

When you pass
    done: $('.loading').removeClass('loading').addClass('loaded')

It's instantly evaluated. Instead try passing
    done: function() { $('.loading').removeClass('loading').addClass('loaded') }

It's a closure that will be evaluated only after done really fires.

**Comment by minddust** [comment]
@ptihiy yep. thanks for replying :)
